### ISSUE TITLE
Feature Request: Bookmarklet

### ISSUE THREAD

**Issue by mschatz** [tbtlr/gordon#3]
This is a really cool project. You will rule the world if you create a bookmarklet that lets you use gordon to render swf files on-the-fly. This would help, for example, to render swf files on the iPhone that can't otherwise be seen at all. 

Great Work!

Mike

**Comment by badboy** [comment]
that could be a bit hard. As far as I understand Gordon loads the swf file via an AJAX call but AJAX calls are restricted to the website they are executed from. So loading a SWF file from an extern site is impossible.

**Comment by attilammagyar** [comment]
I've just committed a draft of bookmarklet support into my fork. The relevant commits are:
- https://github.com/attilammagyar/gordon/commit/d63af1d0b09216b28059d77df1c3376ff5ee2a3f
- https://github.com/attilammagyar/gordon/commit/0fe191c843fb0af661046c1b5c6d3f2faf1ac868
- https://github.com/attilammagyar/gordon/commit/0fb45514d3789207646fa336952f87c4c810dc75

This is a first-draft version, it needs to be integrated better into the codebase and some cleanups might be needed here and there, but it seems to work in real-life scenarios. Don't expect a miracle, "work" in this case means that it invokes Gordon and lets it load the SWF. After that usually some JS errors are thrown by Gordon (e.g. "type is not defined" coming from the 126th line of src/renderer/svg.js), so some bugfixes are needed in Gordon itself. It works fine with demo SWFs from http://paulirish.com/work/gordon/demos/ , but I also found some other sites that at least start to render: http://faraday.physics.utoronto.ca/IYearLab/Intros/BoylesLaw ./Flash/piston.html .

**Comment by mschatz** [comment]
Very cool.

Mike

**Comment by eligrey** [comment]
Why not have an anonymous bookmarklet that doesn't leak globals, such as the following?:

```
javascript:document.documentElement.appendChild(document.createElement("script")).src="http://path/to/bookmarklet/gordonbm.js";
```

**Comment by attilammagyar** [comment]
Thanks for the advice, I committed it here: https://github.com/attilammagyar/gordon/commit/313956ffa917da2c34040206a3d85ccb738f1a21 .
